# Temario {.unnumbered}

- Introducción al aprendizaje de máquina
- Principios de aprendizaje supervisado
- Regresión lineal
- Métodos de remuestreo y validación cruzada
- Principios de Regularización
- Problemas de clasificación, métricas y evaluación
- Árboles, bosques aleatorios y boosting
- Redes neuronales
- Métodos no supervisados

### Evaluación {.unnumbered}

- Tareas (20%)
- Examen parcial (20%)
- Proyecto final (30%):
  - Entrega (75%)
  - Exposición (25%)  
- Examen final (30%)

Existirá una parte extra a los alumnos que contribuyan al aprendizaje de sus compañeros:

- Contribuciones al repositorio: añadiendo redacción más entendible, añadiendo ejemplos particulares a sus carreras, etc.
- Actividad en el canal de Slack: contestando dudas de sus compañeros, iniciando discusiones para resolver problemas. 

### Profesor

**Nombre**: Saúl Caballero Ramírez

**Correo**: saul.caballero.ramirez@gmail.com

**Correo alternativo**: saul@nixtla.io

El canal más rápido y efectivo será el siguiente canal de **[Slack](https://join.slack.com/t/mineriadedatosgrupo/shared_invite/zt-3bop206bb-BIXS8DXRH46~ezS_Jb1w7Q)**. La idea de este canal es que puedan comunicarse entre ustedes para ayudarse a aprender y si necesitan de mi ayuda intentaré contestar en un periodo corto de tiempo. Cualquier comportamiento inadecuado dentro de este foro será penalizado por las reglas de convivencia del ITAM.

### Referencias principales {.unnumbered}

- [An Introduction to Statistical Learning](https://www.statlearning.com/), @ISL 
- [The Elements of Statistical Learning](https://hastie.su.domains/ElemStatLearn/), @ESL 